### ISSUE TITLE
Issue with mininet_1.py?

### ISSUE THREAD

**Issue by zohaib-latif-3** [iist-sysnet/OpenSDNDataset#3]
Hello,
Mininet_1.py is not working. I am getting following error.
Traceback (most recent call last):
  File "mininet_1.py", line 423, in <module>
    simpleTest()
  File "mininet_1.py", line 299, in simpleTest
    if(int(sys.argv[2]) % 2 == 1):
IndexError: list index out of range

Is there anything I am doing wrong?

**Comment by RajalakshmiUma** [comment]
Hello...,
I am also having this error. Can you please tell me how you rectify this error.

**Comment by anandsanto** [comment]
Hi Zohaib and Rajalakshmi, mininet_1.py expects few command line arguments. First arg being the path at which mininet_1.py writes its outputs, The second argument being the current iteration number. 

mininet_1.py is supposed to be run by pyscript file which sets up the path and calls it with right number of arguments. 

Even though the code is totally functional, I understand that it is not in a state where a new person could understand and work with it right away. For now, please start with pyscript file and work your way upto mininet_1.py.

I'll try to find some time soon and make the tool much more cleaner and user friendly.
