### ISSUE TITLE
Missing global.pkl file

### ISSUE THREAD

**Issue by SalonaChoudhury** [iist-sysnet/OpenSDNDataset#4]
Hi,
   On running the pyscript file, I'm getting this error:

Starting Mininet...
Traceback (most recent call last):
  File "mininet_1.py", line 423, in <module>
    simpleTest()
  File "mininet_1.py", line 310, in simpleTest
    with open("global.pkl", 'r') as f:
IOError: [Errno 2] No such file or directory: 'global.pkl'
Start the Controller code and wait...
('Killing ', 18137, ' Mininet')
('Killing ', 18140, ' Controller')
('Killing ', 18140, ' Controller')
('Killing ', 18136, ' TCPdump')
iperf: no process found
ITGRecv: no process found
Killed tcpdump(8327) with signal 9
Killed tcpdump(14593) with signal 9
Killed tcpdump(18136) with signal 9
ruby: no process found
Killed ryu-manager(18142) with signal 9
tshark: no process found
Running 3 of total 3000 iterations
Clearing previous instances of mininet...

**Comment by SalonaChoudhury** [comment]
That file is not present in the downloaded files.

**Comment by anandsanto** [comment]
Hi Salona,

That file is created dynamically on run time. For now check if all the dependencies and path are correct in all the files. Meanwhile, we are working on a solid upgrade to the dataset generation program which should be out soon.

**Comment by SalonaChoudhury** [comment]
Sir,
    Thanks for replying back. Actually we need a SDN dataset (of network
traffic) for our college project, involving machine learning.

    If you have a dataset with you, kindly send it to me, for which we
would be very grateful.

Thanks in advance
Regards,
Salona Choudhury
